### ISSUE TITLE
sql backup file pattern

### ISSUE THREAD

**Issue by theodorosploumis** [dropdog/docs#3]
A question for the [db backups](https://github.com/dropdog/docs/blob/master/docs/development.md#dealing-with-backups).

Do you know if there is any issue with unix and other host servers when using files with the ":" symbol?

```
livedb-2016-01-29T14:04:46+02:00.sql
```

**Comment by theodorosploumis** [comment]
Would it be better to use this pattern (see the format characters from http://php.net/manual/en/function.date.php)?

```
# Y-m-d\TH-i-sO.sql
2016-01-29T14-30-28+0200.sql
```

**Comment by hostdog** [comment]
Allowed characters is a file system characteristic-limitation, unix and
ext4 has no limitations except 2 characters "/", "\0"
