### ISSUE TITLE
Need a license for docs

### ISSUE THREAD

**Issue by theodorosploumis** [dropdog/docs#5]
I realized we have no license for these docs. We have to decide asap because Google indexes the pages. Proposed licenses are:
- [Creative commons](https://creativecommons.org/choose/)
- [Open Publication License](http://opencontent.org/openpub/)
- [GNU Free Documentation License](http://www.gnu.org/licenses/fdl.html)

Please propose yours and let me know.

**Comment by hostdog** [comment]
I don't like Creative Common.
I am ok with Open Publication License or GNU. 
For documentation I prefer GNU.

**Comment by theodorosploumis** [comment]
Will use the GNU Free Documentation license then. Can we use the **company name** as the copyright holder? Please advise.

```
Copyright (C)  2016  YOUR NAME.
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in the section entitled "GNU
    Free Documentation License".
```

**Comment by theodorosploumis** [comment]
As I see again, GNU Free Docs license says:

`Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.`

But we would like to have changes by people, right? This will not allow for modifications.

**Comment by hostdog** [comment]
Ok go with open doc.

Yes you can use company name.

On Friday, 4 March 2016, Theodoros Ploumis notifications@github.com wrote:

> As I see again, GNU Free Docs license says:
> 
> Everyone is permitted to copy and distribute verbatim copies of this
> license document, but changing it is not allowed.
> 
> But we would like to have changes by people, right? This will not allow
> for modifications.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dropdog/docs/issues/5#issuecomment-192268593.

## 

Kind regards,

_Hostdog Team_
Account dep.
https://www.hostdog.gr/  M. Alexandrou 9 ave
http://maps.google.com/maps/ms?msid=203048164876380838907.0004b1b642d65a9dd425d&msa=0,
546 40 Thessaloniki, Greece
Tel. :+30 2310 863288
Hostdog.gr https://www.hostdog.gr/ - Google+
https://plus.google.com/+HostdogGr - Twitter
https://twitter.com/hostdog_gr - Facebook
https://www.facebook.com/greek.hosting - LinkedIn
https://www.linkedin.com/company/3067495
_Confidentiality Notice_: This e-mail and any attachments hereto may
contain information that is privileged or confidential, and is intended for
use only by the individual or entity to which it is addressed. Any
disclosure, copying or distribution of the information by anyone else is
strictly prohibited. If you have received this document in error, please
notify us. _Thank you_.

**Comment by theodorosploumis** [comment]
Close with 6956bb6d (with wrong link to #3!)

**Comment by hostdog** [comment]
Please change hostdog.gr to hostdog.eu

> Copyright (c) 2016 by Hostdog.gr
